packages:
  - apps/adminpanel
  - apps/backend
  - apps/web
  - packages/config
  - packages/database
  - packages/shareds
allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - hono@4.13.3
